filenames = ...
{...
  'voice/man1.wav',...
  'voice/man2.wav',...
  'voice/HUMAN_ACAPELLA_SHO_DO_WOP_DO_AHH_01.wav',...
  'voice/HUMAN_VOICE_SING_FIESTA_01.wav',...
  'voice/woman1.wav',...
  'voice/woman2.wav',...
  'voice/woman3.wav',...
  'voice/woman4.wav',...
  'voice/atomicPlayboy2.wav',...
  'drums/drum1.wav',...
  'drums/drum2.wav',...
  'drums/drum3.wav',...
  'drums/drum4.wav',...
  'drums/drum5.wav',...
  'drums/drum6.wav',...
  'drums/drum7.wav',...
  'drums/drum8.wav',...
  'drums/drum9.wav',...
  'drums/drum10.wav',...
  'drums/drum11.wav',...
  'drums/drum12.wav',...
  'drums/drum13.wav',...
  'drums/drum14.wav',...
  'drums/drum15.wav',...
  'drums/drum16.wav',...
  'drums/drum17.wav',...
  'drums/drum18.wav',...
  'drums/drum19.wav',...
  'drums/drum20.wav',...
  'drums/drum21.wav',...
  'drums/drum22.wav',...
  'drums/drum23.wav',...
  'drums/drum24.wav',...
  'drums/drum25.wav',...
  'drums/drum26.wav',...
  'drums/drum27.wav',...
  'drums/drum28.wav',...
  'drums/drum29.wav',... 
  'drums/drum30.wav',...
}

for f = filenames
  filename = f{1}
  doPitch
end