filenames = ...
{ 'drums/drum1', ...
  'drums/drum2', ...
  'drums/drum3', ...
  'drums/drum4', ...
  'drums/drum5', ...
  'drums/drum6', ...
  'drums/drum7', ...
  'drums/drum8', ...
  'drums/drum9', ...
  'drums/drum10', ...
  'drums/drum11', ...
  'drums/drum12', ...
  'drums/drum13', ...
  'drums/drum15', ...
  'drums/drum17', ...
  'drums/drum18', ...
  'drums/drum20', ...
  'drums/drum21', ...
  'drums/drum22', ...
  'drums/drum23', ...
  'drums/drum24', ...
  'drums/drum25', ...
  'drums/drum27', ...
  'drums/drum29', ...
  'drums/drum30'};
  
for k = 1:length(filenames)
  tmp = doit(filenames{k}, true);
end 